### ISSUE TITLE
Create github action to run build in pull request

### ISSUE THREAD

**Issue by wmcheung** [Project-Catalyst/project-catalyst.github.io#162]
Creating a Github action that runs the build in pull request will be a good way to avoid hotfixes like https://github.com/Project-Catalyst/project-catalyst.github.io/pull/161.

**Comment by fhilipk** [comment]
Lets get a few votes on to this and test our first community added, voted and bounty assigned issue resolution.

**Comment by fhilipk** [comment]
Bounty Level: Important
Complexity: Simple
Bounty: 5 Ada
Bounty Bonus: 5 Ada
Admin bounty: 2 Ada
Increase increment: 7 days

**Comment by mwojtera** [comment]
Closing it. Works like a charm.

**Comment by fhilipk** [comment]
Great work @wmcheung. Thank you for your participation and support.
