### ISSUE TITLE
Create Proposer Resources Page

### ISSUE THREAD

**Issue by mwojtera** [Project-Catalyst/project-catalyst.github.io#49]
Page with resources specific for 
![proposer_resources](https://user-images.githubusercontent.com/1488095/111810147-fc76fc80-88d5-11eb-8466-c71f8856e48c.png)

**Comment by greg-kida** [comment]
@mwojtera has anyone started on this yet? Do we have any resources to pull from as far as content (documents, PDFs, napkin sketches, etc)? Can you share a viewer link to the Miro brainstorm? Would love to help out and put together some mock-ups in Figma for the team.

**Comment by mwojtera** [comment]
@greg-kida Thanks for the offer, if you can help us out that would be great! @fhilipk Am I correct to think that @jacoblambda was doing something with this page? I think Phil has the sharing ability, I can't seem get a sharing link on the Miro board.
